# Generated by Django 4.0.1 on 2022-01-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('size', models.IntegerField(default=0)),
                ('codec', models.CharField(blank=True, max_length=20, null=True)),
                ('lastscan', models.DateField()),
            ],
        ),
    ]
