# Generated by Django 4.0.1 on 2022-01-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffmpeg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='md5hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
