# Generated by Django 4.0.1 on 2022-01-31 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ffmpeg', '0002_mediafile_md5hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediafile',
            old_name='codec',
            new_name='audio_codec',
        ),
        migrations.RenameField(
            model_name='mediafile',
            old_name='md5hash',
            new_name='fingerprint',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='audio_bitrate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='audio_samplerate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='filepath',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediafile',
            name='video_bitrate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='video_codec',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='video_fps',
            field=models.IntegerField(default=0),
        ),
    ]
