# Generated by Django 4.0.1 on 2022-01-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffmpeg', '0003_rename_codec_mediafile_audio_codec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
    ]
