# Generated by Django 4.0.1 on 2022-01-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffmpeg', '0005_alter_mediafile_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='minutes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
