# Generated by Django 4.0.1 on 2022-01-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffmpeg', '0006_alter_mediafile_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='lastscan',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
    ]
