# Generated by Django 4.0.1 on 2022-01-31 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ffmpeg', '0007_alter_mediafile_lastscan_alter_mediafile_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='title',
        ),
    ]
