# Generated by Django 4.0.1 on 2022-02-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffmpeg', '0008_remove_mediafile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='bitrate',
            field=models.IntegerField(default=0),
        ),
    ]
