# Generated by Django 4.0.1 on 2022-02-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffmpeg', '0009_mediafile_bitrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
