# Generated by Django 4.0.1 on 2022-02-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffmpeg', '0013_invalidmediafile_alter_mediafile_audio_bitrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invalidmediafile',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
